### ISSUE TITLE
following README instructions, npm install doesn't work

### ISSUE THREAD

**Issue by isc-rsingh** [cloudant-labs/location-tracker-nodejs#20]
Here's the full error message:

> cloudant-location-tracker@0.0.0 prepublish /Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs
> ./admin.js db put && ./admin.js api set_permissions

Error creating location tracker database
Error creating users database

/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/node_modules/cloudant/cloudant.js:93
    throw new Error('set_permissions requires an "password" parameter during i
          ^
Error: set_permissions requires an "password" parameter during initialization
    at Object.set_permissions (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/node_modules/cloudant/cloudant.js:93:11)
    at Command.<anonymous> (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/admin.js:162:18)
    at Command.listener (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/admin.js:182:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! cloudant-location-tracker@0.0.0 prepublish: `./admin.js db put && ./admin.js api set_permissions`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the cloudant-location-tracker@0.0.0 prepublish script './admin.js db put && ./admin.js api set_permissions'.
npm ERR! This is most likely a problem with the cloudant-location-tracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./admin.js db put && ./admin.js api set_permissions
npm ERR! You can get their info via:
npm ERR!     npm owner ls cloudant-location-tracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajrsingh/workspace/locationtracker/location-tracker-nodejs/npm-debug.log

**Comment by bradley-holt** [comment]
This should be resolved now. Please reopen if not.
